language: objective-c

osx_image: xcode12.5
env:
  matrix:
    - TEST_SDK=iphonesimulator14.5 OS=13.0 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator14.5 OS=14.1 NAME='iPhone X'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project SwiftPersianTools.xcodeproj -scheme SwiftPersianTools -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
